name: Deploy Demo Objects

# Controls when the action will run. 
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt

      # Make sure all 7 SNOWFLAKE_ environment variables are set
      # SnowCLI accesses the passowrd directly from the SNOWFLAKE_PASSWORD environmnet variable
      - name: Deploy notebooks
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > /home/runner/sf_rsa_key.p8
          chmod 600 /home/runner/sf_rsa_key.p8
          snow sql -q "ALTER GIT REPOSITORY DEMO.PYPLINES.REPO_GIT_DEMO_PYPLINES FETCH" --temporary-connection --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USER --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE --database $SNOWFLAKE_DATABASE --schema $SNOWFLAKE_SCHEMA --authenticator SNOWFLAKE_JWT --private-key-file "/home/runner/sf_rsa_key.p8"
          snow sql -q "EXECUTE IMMEDIATE FROM @DEMO.PYPLINES.REPO_GIT_DEMO_PYPLINES/branches/main/scripts/deploy_notebooks.sql USING (env => 'PRO', branch => 'main')" --temporary-connection --account $SNOWFLAKE_ACCOUNT --user $SNOWFLAKE_USER --role $SNOWFLAKE_ROLE --warehouse $SNOWFLAKE_WAREHOUSE --database $SNOWFLAKE_DATABASE --schema $SNOWFLAKE_SCHEMA --authenticator SNOWFLAKE_JWT --private-key-file "/home/runner/sf_rsa_key.p8"
          rm /home/runner/sf_rsa_key.p8

          : # Ideally both Snow CLI and the Python Connector could be configured entirely from env variables
          : #python $GITHUB_WORKSPACE/scripts/deploy_task_dag.py DEMO_DB PROD_SCHEMA
